### ISSUE TITLE
haproxy and lets encrypt error 

### ISSUE THREAD

**Issue by g0ld3lux** [ixc/letsencrypt-dockercloud-haproxy#2]
```
docker_letsencrypt_1 exited with code 1
letsencrypt_1  | [FATAL tini (5)] Executing child process 'entrypoint.sh' failed: 'Permission denied'
```

Im receiving this error if i tried to use this repo to build my image manually
and not one in dockerhub.

im using version 2 of docker-compose

but when i use version 1 

i can use this properly

can you help me out how to properly build this...

seems like im missing something out

**Comment by g0ld3lux** [comment]
here is my docker-compose.yml

```
# Docker Version
version: '2'
# Application Services
services:
  # Load Balancer
  haproxy:
    build: ./haproxy
    networks:
      - front-end
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - letsencrypt
    environment:
      - BALANCE=source
  # SSL Certificate Renewal
  letsencrypt:
    build: ./letsencrypt
    environment:
      - DOMAINS=scalingout.dev,www.scalingout.dev
      - EMAIL=admin@scalingout.dev
    networks:
      - front-end
    expose:
      - "80"
  # Application
  web:
      build: ./web
      environment: 
          # Accept Wildcard
          - VIRTUAL_HOST=*,https://*
          #- FORCE_SSL=yes
      volumes:
          - ./web/config/conf.d:/etc/nginx/conf.d
          - ./web/config/sites-enabled:/etc/nginx/sites-enabled
          # Your Application Code is Located Here
          - ../:/var/www/laravel/
      networks:
        - front-end
        - back-end
  # Database
  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - back-end
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  # Caching
  cache:
    image: redis:alpine
    command: redis-server --requirepass redis --appendonly yes
    volumes:
      - redis:/data
    restart: always
    ports:
      - "6379:6379"
    networks:
      - back-end

# All Volumes
# Default Driver is Local
volumes:
  redis:
    driver: local
  mysql:
    driver: local
# Networking
# Default Network is Bridge , Overlay for Docker Swarm
networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge

```
